.PHONY: local all

local:
	jekyll build --safe -d ./local

test:
	jekyll build --safe -d /Volumes/test.computational.linguistics.illinois.edu/ling402/Fall2018/

all:
	jekyll build --safe -d /Volumes/computational.linguistics.illinois.edu/ling402/Fall2018/
